region                  = "ap-south-2"
ami_id                  = "ami-07891c5a242abf4bc"
instance_type           = "t3.small"
key_name                = "hyd"
iam_instance_profile    = "github-runner-profile"
github_runner_token     = "BI3ZDOARE6PJ7FW5YDQ3MLDIO2ZFY"
aws_account_id          = "390403879955"
alert_email             = "durgap8464@gmail.com"
