region                  = "ap-south-2"
ami_id                  = "ami-07891c5a242abf4bc"
instance_type           = "t3.micro"
key_name                = "hyd"
iam_instance_profile    = "github-runner-profile"
github_runner_token     = "BI3ZDOHKFOO7JJFJAWV5ZRLIOLA6K"
aws_account_id = "390403879955"
