name: Terraform Destroy

on:
  workflow_dispatch:
  push:
    tags:
      - 'destroy'

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
     
      - name: Get EC2 Public IP
        id: get_ip
        run: |
          IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=GitHubRunnerEC2" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "ip=$IP" >> $GITHUB_OUTPUT
    
      - name: Trigger Log Parser Over SSH
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.get_ip.outputs.ip }} \
         'sudo python3 /root/log_parser.py'
